# Generated by Django 5.0 on 2024-02-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='ClassCode')),
                ('subject', models.CharField(max_length=25, verbose_name='Subject')),
                ('teachername', models.CharField(max_length=30, verbose_name='TeacherName')),
            ],
        ),
    ]
