# Generated by Django 4.2.10 on 2024-02-19 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=25)),
                ('teachername', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('date', models.DateField()),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='Class.student')),
                ('test_id', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='Class.test')),
            ],
            options={
                'db_table': 'Result',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('lass_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('class_id', models.ForeignKey(db_column='class_id', default='123456', on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
            ],
            options={
                'db_table': 'Lecture',
            },
        ),
        migrations.CreateModel(
            name='Class_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='Class.teacher')),
            ],
            options={
                'db_table': 'Class_Teacher',
            },
        ),
        migrations.CreateModel(
            name='Class_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='Class.student')),
            ],
            options={
                'db_table': 'Class_Student',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('asgmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
            ],
            options={
                'db_table': 'Assignment',
            },
        ),
        migrations.AddConstraint(
            model_name='class_teacher',
            constraint=models.UniqueConstraint(fields=('class_id', 'teacher_id'), name='unique_class_teacher'),
        ),
        migrations.AddConstraint(
            model_name='class_student',
            constraint=models.UniqueConstraint(fields=('class_id', 'student_id'), name='unique_class_students'),
        ),
    ]
