# Generated by Django 5.0.2 on 2024-02-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
    ]
