# Generated by Django 5.0 on 2024-02-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='Class',
        ),
    ]
