# Generated by Django 5.0.2 on 2024-02-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class'),
        ),
        migrations.AlterField(
            model_name='class_student',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class'),
        ),
        migrations.AlterField(
            model_name='class_student',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='Class.student'),
        ),
        migrations.AlterField(
            model_name='class_teacher',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class'),
        ),
        migrations.AlterField(
            model_name='class_teacher',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='Class.teacher'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lass_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='Class.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='test_id',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='Class.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='Class.class'),
        ),
    ]
