# Generated by Django 5.0 on 2024-02-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
