# Generated by Django 5.0 on 2024-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0004_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Lecture',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachername',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
