# Generated by Django 5.0 on 2024-02-18 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0005_lecture_teacher_remove_class_id_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='class_id',
            field=models.ForeignKey(default='123456', on_delete=django.db.models.deletion.CASCADE, to='Class.class'),
        ),
    ]
