# Generated by Django 5.0 on 2024-02-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0006_remove_lecture_id_lecture_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', default='123456', on_delete=django.db.models.deletion.CASCADE, to='Class.class'),
        ),
    ]
